[package]
name = "zuri_net_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1", features = ["full"]}
quote = "1"
proc-macro2 = "1"
regex = "1"
lazy_static = "1"
