name: Build

on: [push]

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - name: Setup rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - name: Setup deps
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          # wayland deps
          sudo apt-get install libwayland-dev libxkbcommon-dev

      - name: Build zuri
        run: cargo build --release --bin zuri

      - name: Release binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/zuri"
          body: "testing release"
