name: Bump Version
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jefflinse/pr-semver-bump@99d71e35cf07ca6e2e5f1200c5944c1dc74006ff
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
          minor-label: new-feature
          patch-label: bug-fix
          require-release-notes: true
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --
