name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jefflinse/pr-semver-bump@99d71e35cf07ca6e2e5f1200c5944c1dc74006ff
        name: Bump and Tag Version
        id: bump
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
          minor-label: new-feature
          patch-label: bug-fix
          require-release-notes: true
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --

      - name: Setup deps
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          # wayland deps
          sudo apt-get install libwayland-dev libxkbcommon-dev

      - run: rustup update stable && rustup default stable

      - name: Build zuri
        run: cargo build --release --bin zuri

      - name: Release binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/zuri"
          tag: ${{ steps.bump.outputs.version }}
