name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup deps
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          # wayland deps
          sudo apt-get install libwayland-dev libxkbcommon-dev

      - run: rustup update stable && rustup default stable

      - name: Build zuri
        run: cargo build --release --bin zuri

      - name: Release binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/zuri"
          body: "testing release"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/zuri"
